#!/usr/bin/env python3
"""Writes PROGRESS.md (stdout) from the result files; driver.sh runs it after every step."""
import json, os

H = os.path.dirname(os.path.abspath(__file__))


def lines(p):
    try:
        return [json.loads(l) for l in open(os.path.join(H, p)) if l.strip()]
    except FileNotFoundError:
        return []


def count(p):
    try:
        return sum(1 for _ in open(os.path.join(H, p)))
    except FileNotFoundError:
        return 0


steps = [
    ("bisect", "step 0: bisect, 3 variants × 5 reps (bisect/)", f"{count('bisect/done.txt')}/15 runs"),
    ("build", "build the sort-option binaries", ""),
    ("tests", "existing + new tests (tests.log)", ""),
    ("data", "mixgen data, query services", ""),
    ("edge-cpu", "step 1 edge CPU, 8 configs × 2 signals × 5 reps (edge.jsonl)", f"{sum(1 for d in lines('edge.jsonl') if d['pass'] == 'cpu')}/80"),
    ("edge-set", "step 1 object sets (otel/sorting/set/)", f"{sum(1 for d in lines('edge.jsonl') if d['pass'] == 'set')}/16"),
    ("central", "step 1 central INSERT…SELECT, 4 configs × 2 batch sizes × 5 reps (raw/)", f"{len({d['db'] for d in lines('raw/tables.jsonl')})}/40"),
    ("reads-direct", "step 1 direct ranged reads (direct.jsonl)", ""),
    ("reads-ch", "step 1 ClickHouse s3() reads (ch.jsonl, ch-events.jsonl)", f"{count('ch.jsonl')} queries"),
    ("route", "step 2 routed object sets (data/route-*)", f"{count('data/route-done.jsonl')} publishers"),
    ("reads-route", "step 2 reads on routed sets", ""),
]
print("# bench/sorting progress\n")
print("Generated by `progress.py`; `driver.sh` rewrites it after every step.\n")
print("After a container restart: `cd spike/otel-chdb/bench/sorting && setsid nohup bash driver.sh >> driver.log 2>&1 &`")
print("(it starts the services and skips every run that already has a result).\n")
print("| step | what | state | progress |\n|---|---|---|---|")
for k, what, prog in steps:
    st = "done" if os.path.exists(os.path.join(H, "state", k)) else "pending"
    print(f"| {k} | {what} | {st} | {prog} |")
print("\nAnalysis (summarize.py → results.md, route.py → route.md), README and cleanup (S3 otel/sorting/, sort_* databases) run after the last step.")
