#!/usr/bin/env python3
"""Step 2: service-affine routing, N publishers per cluster, on mixgen's mix.

  route.py > route.md

Model (per cluster; 20 clusters; mid scenario rates 30k spans/s and 10k
logs/s per cluster):
  - publisher j's rate r_j: without routing R/N; with routing_key service
    R × (sum of the shares of the services the ring gives j) (mixgen -ring,
    the loadbalancing exporter's crc32 ring with 100 points per endpoint);
  - an object is a batch of min(10k, r_j × T) rows (10k rows or the batch
    timeout T; T = 1 s, with 0.2 s and 5 s beside it);
  - distinct services in one of j's objects: sum over j's services of
    1 − exp(−n_j × s_i / W_j) (Poisson rows per service), checked against the
    generated 10k-row objects (data/*-stats.jsonl);
  - central fixed insert cost: 15 ms per object in one-object statements
    (bench/clean block 2, fixedMs 15.3), 2.1 ms at the consumer's 32 per
    statement;
  - a one-service, one-hour query in one cluster touches every object of the
    cluster-hour without routing, and only the owner publisher's objects
    with routing (the reader computes the owner from the ring and lists
    that producer's prefix); per object it reads what direct.jsonl measured
    for that composition (10k-row objects of the routed sets, the step-1 set
    for no routing), scaled to the object's rows.
"""
import json, math, os, statistics as st, subprocess

H = os.path.dirname(os.path.abspath(__file__))
S = "/tmp/claude-0/-home-user/db86342c-d57d-54b7-95b1-90f220828b73/scratchpad"
RATE = {"traces": 30000, "logs": 10000}
CLUSTERS, B = 20, 10000
FIXED_1, FIXED_32 = 15.0, 2.1
NS = [1, 3, 8, 16]


def ring(n):
    p = f"{H}/data/ring-N{n}.json"
    if not os.path.exists(p):
        out = subprocess.run([f"{S}/sorting/bin/mixgen", "-ring", "-publishers", str(n)], capture_output=True, text=True, check=True).stdout
        open(p, "w").write(out)
    return json.load(open(p))


def pubs(n, routed):
    r = ring(n)
    if not routed:
        allsv = {k: v["share"] for k, v in r.items()}
        return [(1.0 / n, allsv, 1.0) for _ in range(n)]
    out = []
    for j in range(n):
        sv = {k: v["share"] for k, v in r.items() if v["publisher"] == j}
        out.append((sum(sv.values()), sv, sum(sv.values())))
    return out


def scenario(sig, n, routed, T):
    R = RATE[sig]
    objs, rows_tot, svc_w, per = 0.0, 0.0, 0.0, []
    for frac, sv, W in pubs(n, routed):
        r = R * frac
        if r <= 0:
            per.append(None)
            continue
        nj = min(B, r * T)
        o = r / nj
        d = sum(1 - math.exp(-nj * s / W) for s in sv.values())
        objs += o
        rows_tot += r
        svc_w += o * d
        per.append({"rate": r, "rows": nj, "obj_s": o, "services": d, "nsvc": len(sv)})
    return {"obj_s_cluster": objs, "obj_s_fleet": objs * CLUSTERS, "rows_per_obj": rows_tot / objs, "svc_per_obj": svc_w / objs, "per": per}


def measured_services():
    out = {}
    for sig in ("traces", "logs"):
        p = f"{H}/data/{sig}-stats.jsonl"
        if os.path.exists(p):
            out[("none", sig)] = st.mean(len(json.loads(l)["services"]) for l in open(p))
    for f in sorted(os.listdir(f"{H}/data")):
        if f.startswith("route-N") and f.endswith("-stats.jsonl"):
            tag, sig = f[len("route-"):-len("-stats.jsonl")].rsplit("-", 1)
            out[(tag, sig)] = st.mean(len(json.loads(l)["services"]) for l in open(f"{H}/data/{f}"))
    return out


def direct_reads():
    """(set, config, signal, rank) -> median per-object {whole, best} over objects."""
    out = {}
    p = f"{H}/direct.jsonl"
    if not os.path.exists(p):
        return out
    for l in open(p):
        d = json.loads(l)
        for rank in d["objects"][0]["q"]:
            for cols in ("narrow", "all"):
                k = f"{cols}/fg64k/co1024k"
                rec = {}
                for pick in ("whole", "minmax", "bucket"):
                    xs = [o["q"][rank][k].get(pick) for o in d["objects"]]
                    if all(xs):
                        rec[pick] = {"gets": st.mean(x["gets"] for x in xs), "bytes": st.mean(x["bytes"] for x in xs),
                                     "rows": st.mean(x["rows"] for x in xs)}
                rec["size"] = st.mean(o["size"] for o in d["objects"])
                rec["footer"] = st.mean(o["footer"] for o in d["objects"])
                out[(d["set"], d["config"], d["signal"], rank, cols)] = rec
    return out


def main():
    sv = json.load(open(f"{H}/services.json"))
    ms = measured_services()
    print("# Step 2: service-affine routing (generated by route.py)\n")
    print("Model:" + __doc__.split("Model")[1])
    print("## Objects, object size and central fixed insert cost, mid scenario (20 clusters)\n")
    print("Rows per object = min(10k, publisher rate × T). Services per object: the Poisson estimate (in brackets: counted in the generated 10k-row objects, where they exist).\n")
    print("| signal | N | routing | T | objects/s (fleet) | rows/object (mean) | services/object | fixed insert vCPU at 15 ms/object | at 2.1 ms/object (32 per statement) |")
    print("|---|---|---|---|---|---|---|---|---|")
    for sig in ("traces", "logs"):
        for n in NS:
            for routed in (False, True):
                if n == 1 and routed:
                    continue
                for T in (1.0, 0.2, 5.0):
                    s = scenario(sig, n, routed, T)
                    meas = ""
                    if T == 1.0 and not routed and ("none", sig) in ms:
                        meas = f" [{ms[('none', sig)]:.0f} at 10k]"
                    print(f"| {sig} | {n} | {'service' if routed else 'none'} | {T:g} s | {s['obj_s_fleet']:,.0f} | {s['rows_per_obj']:,.0f} | {s['svc_per_obj']:.1f}{meas} | "
                          f"{s['obj_s_fleet'] * FIXED_1 / 1000:.2f} | {s['obj_s_fleet'] * FIXED_32 / 1000:.2f} |")
    if any(k[0] != "none" for k in ms):
        print("\nServices per generated 10k-row object with routing (mixgen -route service, 8 objects per publisher):\n")
        print("| publisher set | signal | services/object |\n|---|---|---|")
        for (tag, sig), v in sorted(ms.items()):
            if tag != "none":
                print(f"| {tag} | {sig} | {v:.1f} |")
    dr = direct_reads()
    if not dr:
        return
    print("\n## One-service, one-hour query in one cluster: objects, GETs and bytes (T = 1 s)\n")
    print("Per object: the direct ranged path's median over the set's objects (footer suffix GET 64 KiB, ranges merged within 1 MiB), "
          "scaled to the scenario's rows per object. 'whole' reads each touched object in one GET. Columns: the narrow projection.\n")
    print("| signal | query service (share) | N | routing | objects touched/h | GETs/h whole | MB/h whole | config | GETs/h pruned | MB/h pruned | pruned/whole bytes |")
    print("|---|---|---|---|---|---|---|---|---|---|---|")
    for sig in ("traces", "logs"):
        for rank, q in sv.items():
            for n in NS:
                for routed in (False, True):
                    if n == 1 and routed:
                        continue
                    s = scenario(sig, n, routed, 1.0)
                    r = ring(n)
                    if routed:
                        j = r[q["service"]]["publisher"]
                        p = s["per"][j]
                        objs_h = p["obj_s"] * 3600
                        rows = p["rows"]
                        setname = f"route/N{n}p{j}"
                    else:
                        objs_h = s["obj_s_cluster"] * 3600
                        rows = s["rows_per_obj"]
                        setname = "set"
                    for cfg, pick in (("b-sorted-1rg", "minmax"), ("d-hash-16rg", "bucket"), ("f-range-16rg", "minmax")):
                        rec = dr.get((setname, cfg, sig, rank, "narrow"))
                        base = dr.get((setname, "a-unsorted", sig, rank, "narrow")) or dr.get(("set", "a-unsorted", sig, rank, "narrow"))
                        if not rec or pick not in rec or not base:
                            continue
                        scale = rows / B
                        whole_b = (base["size"] - base["footer"]) * scale + base["footer"]
                        fr = rec[pick]
                        # footer bytes don't scale; the data part does
                        pr_b = min(fr["bytes"], rec["footer"]) + max(0.0, fr["bytes"] - rec["footer"]) * scale
                        print(f"| {sig} | {rank} {q['service']} ({q['share'] * 100:.2f}%) | {n} | {'service' if routed else 'none'} | {objs_h:,.0f} | "
                              f"{objs_h:,.0f} | {objs_h * whole_b / 1e6:,.0f} | {cfg} ({pick}) | {objs_h * fr['gets']:,.0f} | {objs_h * pr_b / 1e6:,.1f} | {pr_b / whole_b:.2f} |")


if __name__ == "__main__":
    main()
