#!/usr/bin/env python3
"""PROGRESS.md for bench/clean, derived only from the result files on disk
(so it is right after any restart). driver.sh rewrites it after every step.

  progress.py               the markdown
  progress.py --state bN    done | partial | todo   (for driver.sh)
"""
import glob, json, os, sys

C = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NREP = 5


def lines(p):
    return [json.loads(l) for l in open(p) if l.strip()] if os.path.exists(p) else []


def b2():
    dbs = {r["db"] for r in lines(f"{C}/block2/raw/tables.jsonl")}
    want = [f"clean_b2_{root}_m{mb}_r{r}" for r in range(1, NREP + 1) for root in ("small", "large") for mb in (1, 32)]
    have = [d for d in want if d in dbs]
    return have, [d for d in want if d not in dbs]


B3_RUNS = ["traces-100k-tg", "traces-100k", "logs-100k", "number-100k", "histogram-100k", "exphist-100k", "summary-100k",
           "series-100k", "clickstack-sum-100k", "clickstack-histogram-100k"]


def b3():
    have = [r for r in B3_RUNS if os.path.exists(f"{C}/block3/results/{r}/run.json")]
    return have, [r for r in B3_RUNS if r not in have]


B4_LABELS = ["traces-random-ids", "logs-random-ids", "traces-testgen-ids", "B-gauge", "B-sum", "B-number (gauge+sum)", "B-histogram",
             "B-exponential_histogram", "B-summary", "B-series (5 cycles)", "A-sum", "A-gauge", "A-histogram",
             "A-exponential_histogram", "A-summary"]
B4_LABELS += [f"B-{t} no replay" for t in ("gauge", "sum", "histogram", "exponential_histogram", "summary")]
B4_LABELS += [f"A-{t} no replay" for t in ("sum", "gauge", "histogram", "exponential_histogram", "summary")]


def b4():
    got = {r["label"] for r in lines(f"{C}/block4/results.jsonl")}
    return [l for l in B4_LABELS if l in got], [l for l in B4_LABELS if l not in got]


def b5():
    lat = {(r["poll"], r.get("rep")) for r in lines(f"{C}/block5/latency.jsonl")}
    dr = {(r["root"], r["poll"], r["rep"]) for r in lines(f"{C}/block5/drain.jsonl")}
    want_a = [(p, r) for r in range(1, NREP + 1) for p in ("200ms", "1s")]
    want_b = [(root, p, r) for r in range(1, NREP + 1) for root in ("large", "small") for p in ("200ms", "1s")]
    have = [f"a {p} r{r}" for p, r in want_a if (p, r) in lat] + [f"b {x} {p} r{r}" for x, p, r in want_b if (x, p, r) in dr]
    miss = [f"a {p} r{r}" for p, r in want_a if (p, r) not in lat] + [f"b {x} {p} r{r}" for x, p, r in want_b if (x, p, r) not in dr]
    return have, miss


def state(have, miss):
    return "done" if not miss else ("partial" if have else "todo")


def main():
    blocks = {"b2": b2(), "b3": b3(), "b4": b4(), "b5": b5()}
    if "--state" in sys.argv:
        print(state(*blocks[sys.argv[sys.argv.index("--state") + 1]]))
        return
    names = {"b2": "central insert CPU (block2/)", "b3": "merges (block3/)", "b4": "stored bytes (block4/)", "b5": "consumer end to end (block5/)"}
    print("# bench/clean progress\n")
    print("Generated by `lib/progress.py` from the result files; `driver.sh` rewrites it after every step.\n")
    print("After a container restart: `cd spike/otel-chdb/bench/clean && setsid nohup bash driver.sh >> driver.log 2>&1 &`")
    print("(it starts the services each block needs and skips every run that already has a result).\n")
    print("| block | state | done | missing |\n|---|---|---|---|")
    print("| 1 edge encode CPU (block1/) | done | see block1/results.md | – |")
    for k, (have, miss) in blocks.items():
        print(f"| {names[k]} | {state(have, miss)} | {len(have)} | {', '.join(miss[:6]) + (' …' if len(miss) > 6 else '') or '–'} |")
    extra = []
    if not os.path.exists(f"{C}/block3/pool.ok"):
        extra.append("block 3 replay pool not built yet (driver builds it before block 4)")
    if not os.path.exists(f"{C}/block2/results.md"):
        extra.append("block2/results.md not generated yet")
    if not os.path.exists(f"{C}/README.md"):
        extra.append("README.md (deliverable) not written yet")
    order = "Order: block 2 → block 3 prep → block 4 → block 3 runs → block 5 → analysis, README, cleanup (S3 otel/clean/, private CH wipe)."
    print("\n" + order)
    if extra:
        print("\nNext / open:\n" + "\n".join(f"- {e}" for e in extra))


if __name__ == "__main__":
    main()
